# Generated by Django 2.2.7 on 2020-11-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='confom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=120)),
                ('resvno', models.CharField(default='', max_length=120)),
                ('name', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=50)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('bookIn', models.CharField(blank=True, default='', max_length=50)),
                ('bookOut', models.CharField(blank=True, default='', max_length=50)),
                ('roomname', models.CharField(choices=[('Standard Room', 'Standard Room'), ('Bougainvilla Room', 'Bougainvilla Room'), ('Rose Room', 'Rose Room'), ('Dahlia Room', 'Dahlia Room'), ('Orchid Room', 'Orchid Room'), ('King Orchid', 'King Orchid'), ('Deluxe Villa', 'Deluxe Villa'), ('Luxury Villa', 'Luxury Villa')], db_column='Room Name', default='', max_length=100)),
                ('roomamt', models.CharField(blank=True, default='', max_length=50)),
                ('noofroom', models.CharField(blank=True, default='', max_length=15)),
                ('adult', models.CharField(blank=True, default='', max_length=15)),
                ('exper', models.CharField(blank=True, default='', max_length=15)),
                ('kids', models.CharField(blank=True, default='', max_length=15)),
                ('amount', models.CharField(blank=True, default='', max_length=10)),
                ('t', models.CharField(blank=True, default='', max_length=10)),
                ('tamount', models.CharField(blank=True, default='', max_length=10)),
                ('razorpayid', models.CharField(default='', max_length=255)),
                ('payment_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(choices=[('Standard Room', 'Standard Room'), ('Bougainvilla Room', 'Bougainvilla Room'), ('Rose Room', 'Rose Room'), ('Dahlia Room', 'Dahlia Room'), ('Orchid Room', 'Orchid Room'), ('King Orchid', 'King Orchid'), ('Deluxe Villa', 'Deluxe Villa'), ('Luxury Villa', 'Luxury Villa')], max_length=50)),
                ('roomtype', models.CharField(choices=[('Room', 'Room'), ('Villa', 'Villa')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='webapp/static/Room')),
                ('dis', models.CharField(db_column='Room Description', default='', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Roomimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateimg', models.ImageField(null=True, upload_to='webapp/static/Room')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=50)),
                ('bookIn', models.CharField(blank=True, default='', max_length=50)),
                ('bookOut', models.CharField(blank=True, default='', max_length=50)),
                ('roomname', models.CharField(choices=[('Standard Room', 'Standard Room'), ('Bougainvilla Room', 'Bougainvilla Room'), ('Rose Room', 'Rose Room'), ('Dahlia Room', 'Dahlia Room'), ('Orchid Room', 'Orchid Room'), ('King Orchid', 'King Orchid'), ('Deluxe Villa', 'Deluxe Villa'), ('Luxury Villa', 'Luxury Villa')], db_column='Room Name', default='', max_length=100)),
                ('roomamt', models.CharField(blank=True, default='', max_length=50)),
                ('noofroom', models.CharField(blank=True, default='', max_length=15)),
                ('adult', models.CharField(blank=True, default='', max_length=15)),
                ('exper', models.CharField(blank=True, default='', max_length=15)),
                ('kids', models.CharField(blank=True, default='', max_length=15)),
                ('amount', models.CharField(blank=True, default='', max_length=10)),
                ('t', models.CharField(blank=True, default='', max_length=10)),
                ('tamount', models.CharField(blank=True, default='', max_length=10)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('razorpayid', models.CharField(default='', max_length=255)),
                ('payment_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', default='', max_length=50)),
                ('mobile', models.CharField(db_column='Mobile', default='', max_length=10)),
                ('email', models.CharField(db_column='Email', default='', max_length=100)),
                ('pass1', models.CharField(db_column='Password', default='', max_length=100)),
                ('admin_status', models.BooleanField(default=False)),
                ('radmin_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
