# Generated by Django 3.1.6 on 2021-09-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210901_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(null=True, upload_to='static/Room'),
        ),
    ]
