# Generated by Django 3.1.6 on 2021-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210909_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(null=True, upload_to='webapp/static/Room'),
        ),
    ]
