# Generated by Django 3.1.6 on 2021-09-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210909_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='roomimg',
            name='updateimg',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
    ]
