# Generated by Django 3.1.6 on 2021-09-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210913_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
                ('feedback', models.CharField(blank=True, default='', max_length=500000)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='date_disable',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='date_disable1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='date_disable2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
